export enum Markdown{
    H1 = "#",
    H2 = "##",
    H3 = "###",
    H4 = "####",
    H5 = "#####",
    H6 = "######",
    BOLD = "**",
    ITALIC = "*",
    UNDERLINE = "__",
    STRIKETHROUGH = "~~",
    CODE = "`",
    CODEBLOCK = "```",
    QUOTE = ">",
    BULLET = "-",
    NUMBERED = "1.",
    CHECKBOX = "- [ ]",
    LINK = "[",
    IMAGE = "![",
    TABLE = "|",
    LIST = "-",
    LINE = "---",
    TAB = "\t",
    NEWLINE = "\n"
}